homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('aboutus/', views.about, name='about'),
    path('competitions/', views.competitions, name='competitions'),
    path('booklets/', views.booklets, name='booklets'),
    path('timeline/<str:competition>/', views.timeline, name='timeline'),
    path('gallery/', views.gallery, name='gallery'),\
    path('pagenotavailable/', views.pagenotavailable, name='pagenotavailable'),
]

oim2021/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

handler404 = 'homepage.views.handler404'
handler500 = 'homepage.views.handler500'

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.

def about(request):
    return render(request, 'about.html')

def competitions(request):
    return render(request, 'competitions.html')

def booklets(request):
    return render(request, 'booklets.html')

def timeline(request, competition):
    url = ''
    if competition == "debat" :
        url = 'timeline_debat.html'
    elif competition == "quiz":
        url = 'timeline_quiz.html'
    elif competition == "essay":
        url = 'timeline_essay.html'
    elif competition == "poster":
        url = 'timeline_poster.html'
    elif competition == "pkmai":
        url = 'timeline_pkmai.html'
    elif competition == "pkmgfk":
        url = 'timeline_pkmgfk.html'
    elif competition == "pkmgt":
        url = 'timeline_pkmgt.html'
    elif competition == "pkmk":
        url = 'timeline_pkmk.html'
    elif competition == "pkmkc":
        url = 'timeline_pkmkc.html'
    elif competition == "pkmpi":
        url = 'timeline_pkmpi.html'
    elif competition == "pkmpm":
        url = 'timeline_pkmpm.html'
    elif competition == "pkmr":
        url = 'timeline_pkmr.html'
    elif competition == "all":
        url = 'timeline.html'
    else :
        url = 'error/404.html'
    return render(request, url)

def handler404(request, exception):
    return render(request, 'error/404.html',status=404)

def handler500(request):
    return render(request, 'error/500.html', status=500)

def gallery(request):
    return render(request, 'gallery.html')

def pagenotavailable(request):
    return render(request, '503.html')   

def homepage(request):
    return render(request, 'homepage.html')

homepage/templates/503.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    503
{% endblock title %}

{% block content %}
    <div class="container" style="height: 100vh; width: 100vw;">
        <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%)">
            <div class="row justify-content-center">
                <img src="{% static 'images/others/404.png' %}" height="200px" alt="">
            </div>
            <div style="height: 30px;"></div>
            <div class="row justify-content-center" style="text-align: center;">
                <h1 style="font-size: 36px;color: #742d7e;">This page is not yet available.</h1>
            </div>
            <div style="height: 30px;"></div>
            <div class="row justify-content-center">
                <a class="mybutton purple" onclick="goBack()">Sorry. I'll go back.</a>
            </div>
        </div>
    </div>
{% endblock content %}

homepage/templates/gallery.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Gallery
{% endblock title %}
    
{% block content %}
{% include 'navbar.html' %}
    <script src="{% static 'javascript/jquery.visible.js' %}"></script>
    <script src="{% static 'javascript/gallery.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    <div class="fore" id="pic_overlay">
        <div class="container-md">
            <div class="row">
                <div class="col-lg" style="object-fit: cover; display: inline-block; margin-bottom: 30px;">
                    <a id="open_pic"  target="_blank" href="" style="height: 100%;">
                        <img id="pic" style="min-height: 150px;" src="{% static 'images/others/Logo.png' %}" alt="judul" width="100%">
                        <h2 id="open_pic_message" style="font-size: 24px; margin-bottom: 0;">Click to zoom/download the picture</h2>
                    </a>
                </div>
                <div class="col-lg" style="overflow-y: auto; max-height: 50vh;">
                    <!-- <div class="onlymobile" style="height: 30px;"></div> -->
                    <h2 class="loading" id="pic_judul">Lorem Ipsum</h2>
                    <p class="loading" id="pic_deskripsi">
                        Is simply dummy text of the printing and typesetting industry. 
                        Lorem Ipsum has been the industry's standard dummy text ever 
                        since the 1500s, when an unknown printer took a galley of type 
                        and scrambled it to make a type specimen book.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <h1 class="header">Gallery</h1>
    <div class="container-lg">
        <div class="small"></div>
        <h2  style ="color: #0e1738;">Events</h2>
        <div class="row">
            <!-- {% for pic in event %}
                <div class="col col_frame">
                    <div class="frame loading" onclick="openpic('{{pic.id_dok}}')">
                        <img src="" alt="pic.judul" >
                    </div>
                </div>
            {% endfor %}     -->
        </div>
        <div class="divider small"></div>
        <h2  style ="color: #0e1738;">Posters</h2>
		<!-- <div class="row"> 
            {% for pic in poster %}
                <div class="col col_frame">
                    <div class="frame loading" onclick="openpic('{{pic.id_dok}}')">
                        <img src="" alt="pic.judul">
                    </div>
                </div>
            {% endfor %}   
        </div> -->
        <div class="medium"></div>
    </div>
    {% include 'footer.html' %}
{% endblock content %}

homepage/templates/navbar.html
{% load static %}
<script src="{% static 'javascript/navbar.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<nav>
	<a class="logo_mobile" href="{% url 'homepage:homepage' %}"><img src="/static/images/others/logohdd.png" height="30px" alt="OIM 2021"></a>
	<div class="navi">
		<div class="hamburger">
			<img class="dropdown" src="{% static 'images/others/dropdown.svg' %}" height="15px" alt="Dropdown">
		</div>
		<div class="container" style="height: 100%;">
			<div class="row" style="height: inherit;">
				<div class="col-3 onlypc">
					<a class="logo_pc" href="{% url 'homepage:homepage' %}"><img height="60px" src="/static/images/others/logohdd.png" alt="OIM 2021"></a>
				</div>
				<div class="col" style="padding-right: 15px;">
					<ul class="nav-links" >
						<li><a href="{% url 'homepage:about' %}" style="color: #0e1738;">About Us</a></li>
						<li><a href="{% url 'homepage:gallery' %}" style="color: #0e1738;">Gallery</a></li>
						<li><a href="{% url 'homepage:competitions' %}" style="color: #0e1738;">Competitions</a></li>
						<li><a href="{% url 'homepage:timeline' 'all' %}" style="color: #0e1738;">Timeline</a></li>
						<li><a href="{% url 'homepage:booklets' %}" style="color: #0e1738;">Booklets</a></li>
						<div class="onlypc" style="width: 15px;"></div>
						<li><a onclick="uploadon('upload_foreground_daftar')" class="mybutton purple">Daftar</a></li>
					</ul>
				</div>
			</div>
		</div>
        <!-- Farizio was here -->
	</div>
</nav>

homepage/templates/overlay_pkmai.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/overlay.css' %}">
<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_sub_open">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Submission Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:#af43be">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Thu, Sept 23 2021 <br>08:30 WIB – 18:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://bit.ly/PENGUMPULANPKMOIMUI2021" class="mybutton purple" id="overlay_linklomba">Submit Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_sub_open_1">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Submission Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:#af43be">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Thu, Sept 23 2021 <br>00:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://bit.ly/PENGUMPULANPKMOIMUI2021" class="mybutton purple" id="overlay_linklomba">Submit Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_sub_close">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Submission Closed</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:#af43be">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Thu, Oct 14 2021 <br>23:59 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://bit.ly/PENGUMPULANPKMOIMUI2021" class="mybutton purple" id="overlay_linklomba">Submit Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_video_open">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Video Upload Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:#af43be">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Mon, Oct 04 2021 <br>00:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://bit.ly/PENGUMPULANPKMOIMUI2021" class="mybutton purple" id="overlay_linklomba">Upload Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_video_close">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Video Upload Closed</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:#af43be">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Sun, Oct 24 2021 <br>23:59 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>
                <a href="https://bit.ly/PENGUMPULANPKMOIMUI2021" class="mybutton purple" id="overlay_linklomba">Upload Now</a>
                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_proposal_open">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #af43be;" >Proposal Grading Open</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:#af43be">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Mon, Oct 18 2021 <br>00:00 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>

                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>
 
<div style="color: #0e1738;" class="fore overlay_foreground pkmai" id="pkmai_proposal_close">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 nopadding overlay_left" style="margin-right: 10px;">
                <h1 id="overlay_namalomba" style="color: #0e1738;">PKM AI</h1>
                <p id="overlay_deskripsi" style="margin-bottom: 0px;color: #0e1738;" >Proposal Grading Closed</p>
                <a class = "reg_link" href="{% url 'homepage:timeline' 'pkmai' %}" id="overlay_viewnamalomba" class="loading" style="color:#af43be">View All PKM AI Events</a>
                <div style="height: 20px;"></div>
                <p class="bold" id="overlay_waktu" style="color: #0e1738;"> Sun, Nov 14 2021 <br>23:59 WIB</p>
                <div class="alamat">
                    <p class="namatempat" style="margin-bottom: 0px;color: #0e1738;" id="overlay_tempat">Website</p>
                    <div style="width: 5px"></div>
                    <!-- <a class = "reg_link" href="{% url 'homepage:pagenotavailable' %}" target="_blank" id="reg">View Registration Link</a> -->
                </div>
                <div style="height: 20px;"></div>

                <div style="height: 30px;"></div>
            </div>
            <div class="col-sm participant" id="overlay_partisipan">

            </div>
        </div>
    </div>
</div>

homepage/templates/timeline_essay.html
{% extends 'base.html' %}
<html lang="en">
{% load static %}


{% block title %}
Esai
{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
{% include 'overlay_essay.html' %}

<div class="container header_timeline essay">
    <div class="row">
        <div class="col-md onlymobile" style="height: 150px;"></div>
        <div class="col-md">
            <h1 style="color: #0e1738;">Esai</h1>
            <p style="color: #0e1738;">
                Kompetisi Esai menjadi sarana mahasiswa untuk menunjukkan kemampuannya dalam menulis tulisan yang berisi 
                ide atau gagasan kreatif dengan berpola-pikir ilmiah.  Mahasiswa diharap agar dapat menemukan ide atau 
                gagasan kreatif yang dapat membantu negeri dan masyarakat dalam menyelesaikan permasalahan-permasalahan yang ada. 
                Kemampuan peserta dalam public speaking juga akan diuji  dalam presentasi berbentuk video dan pemahaman peserta 
                atas esai yang ditulis akan diuji dalam sesi tanya jawab dengan para juri.
            </p>
        </div>
        <div class="col-md"></div>
    </div>
    <hr style="margin-top: 60px;">
</div>

<div class="container">
    <div class="small"></div>
    <div class="row justify-content-center">
        <a href="{% url 'homepage:timeline' 'all' %}" class="mybutton purple">View All Timelines</a>
    </div>	
    <div class="small"></div>
        <h2 style="color: #0e1738;">Oct. 18, 2021</h2>
        <div class="row">
                <div class="col compe_col">
                    <div class="compe essay" onclick="uploadon('esai_sub_open_1')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">00:00 WIB</p>
                        <p style="color: #ddd">Submission Open</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
                <div class="col compe_col">
                    <div class="compe essay" onclick="uploadon('esai_vid_open')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">00:00 WIB</p>
                        <p style="color: #ddd">Video Upload Open</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
        </div>
        <div style="height: 15px;"></div>
        <h2 style="color: #0e1738;">Nov. 03, 2021</h2>
        <div class="row">
                <div class="col compe_col">
                    <div class="compe essay" onclick="uploadon('esai_sub_close')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">21:00 WIB</p>
                        <p style="color: #ddd">Submission Closed</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
                <div class="col compe_col">
                    <div class="compe essay" onclick="uploadon('esai_vid_close')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">21:00 WIB</p>
                        <p style="color: #ddd">Video Upload Closed</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
        </div>
        <div style="height: 15px;"></div>
        <h2 style="color: #0e1738;">Nov. 11, 2021</h2>
        <div class="row">
                <div class="col compe_col">
                    <div class="compe essay" onclick="uploadon('esai_quest')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">08:30 WIB – 15:00 WIB</p>
                        <p style="color: #ddd">Question Section</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Youtube</p>
                        </div>
                    </div>
                </div>
        </div>
        <div style="height: 15px;"></div>
</div>
<!-- Lmao just start putting my name everywhere -->
<div class="medium"></div>
{% include 'footer.html' %}

{% endblock %}

homepage/templates/timeline_pkmai.html
{% extends 'base.html' %}
<html lang="en">
{% load static %}


{% block title %}
PKM AI
{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
{% include 'overlay_pkmai.html' %}

<div class="container header_timeline pkmai">
    <div class="row">
        <div class="col-md onlymobile" style="height: 150px;"></div>
        <div class="col-md">
            <h1 style="color: #0e1738;">PKM AI</h1>
            <p style="color: #0e1738;">
                PKM diluncurkan oleh Ditjen Belmawa (Kemendikbud) yang merupakan kompetisi tingkat nasional bidang 
                penalaran dengan memfasilitasi potensi yang dimiliki mahasiswa Indonesia untuk menumbuhkan, mewadahi, 
                dan mewujudkan ide kreatif dan inovatif mahasiswa.
                Artikel ilmiah hasil kegiatan akademik mahasiswa
            </p>
        </div>
        <div class="col-md"></div>
    </div>
    <hr style="margin-top: 60px;">
</div>

<div class="container">
    <div class="small"></div>
    <div class="row justify-content-center">
        <a href="{% url 'homepage:timeline' 'all' %}" class="mybutton purple" >View All Timelines</a>
    </div>	
    <div class="small"></div>
        <h2 style="color: #0e1738;">Sept. 23, 2021</h2>
        <div class="row">
                <div class="col compe_col">
                    <div class="compe pkmai" onclick="uploadon('pkmai_sub_open_1')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">00:00 WIB</p>
                        <p style="color: #ddd">Submission Open</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
        </div>
        <div style="height: 15px;"></div>
        <h2 style="color: #0e1738;">Oct. 04, 2021</h2>
        <div class="row">
                <div class="col compe_col">
                    <div class="compe pkmai" onclick="uploadon('pkmai_video_open')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">00:00 WIB</p>
                        <p style="color: #ddd">Video Upload Open</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
        </div>
        <div style="height: 15px;"></div>
        <h2 style="color: #0e1738;">Oct. 14, 2021</h2>
        <div class="row">
                <div class="col compe_col">
                    <div class="compe pkmai" onclick="uploadon('pkmai_sub_close')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">23:59 WIB</p>
                        <p style="color: #ddd">Submission Closed</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
        </div>
        <div style="height: 15px;"></div>
        <h2 style="color: #0e1738;">Oct. 18, 2021</h2>
        <div class="row">
                <div class="col compe_col">
                    <div class="compe pkmai" onclick="uploadon('pkmai_proposal_open')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">00:00 WIB</p>
                        <p style="color: #ddd">Proposal Grading Open</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
        </div>
        <div style="height: 15px;"></div>
        <h2 style="color: #0e1738;">Oct. 24, 2021</h2>
        <div class="row">
                <div class="col compe_col">
                    <div class="compe pkmai" onclick="uploadon('pkmai_video_close')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">23:59 WIB</p>
                        <p style="color: #ddd">Video Upload Closed</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
        </div>
        <div style="height: 15px;"></div>
        <h2 style="color: #0e1738;">Nov. 14, 2021</h2>
        <div class="row">
                <div class="col compe_col">
                    <div class="compe pkmai" onclick="uploadon('pkmai_proposal_close')" style="min-height: 180px;">
                        <p class="bold" style="margin-bottom: 5px;color: #ddd">23:59 WIB</p>
                        <p style="color: #ddd">Proposal Grading Close</p>
                        <div class="bottom_text">
                            <p style="color: #ddd">Website</p>
                        </div>
                    </div>
                </div>
        </div>
        <div style="height: 15px;"></div>
</div>
<!-- Lmao just start putting my name everywhere -->
<div class="medium"></div>
{% include 'footer.html' %}

{% endblock %}